In [1]:
# Install pandas

import pandas as pd

In [2]:
df = pd.read_csv("../dataset/Online Retail.csv")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [3]:
# Initial Dataset Overview

df.shape

(541909, 8)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   541909 non-null  int64
 7   Country      541909 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 33.1 MB

In [5]:
# Check Missing Values

df.isnull().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64

In [6]:
# Removed missing values

df = df.dropna(subset=["Description"])


df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
# Check Duplicate

df.duplicated().sum()

np.int64(5268)

In [8]:
# Removed Duplicate

df = df.drop_duplicates()

df.duplicated().sum()

np.int64(0)

In [9]:
# Converted Data Types

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df.info()

<class 'pandas.DataFrame'>
Index: 535187 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    535187 non-null  str
 1   StockCode    535187 non-null  str
 2   Description  535187 non-null  str
 3   Quantity     535187 non-null  int64
 4   InvoiceDate  535187 non-null  datetime64[us]
 5   UnitPrice    535187 non-null  float64
 6   CustomerID   535187 non-null  int64
 7   Country      535187 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 36.7 MB

In [10]:
# Check Negative Quantity Values

df["Quantity"].describe()

(df["Quantity"] < 0).sum()

np.int64(9725)

In [11]:
# Removed Negative Quantity Values

df = df[df["Quantity"] > 0]

df["Quantity"].describe()

count    525462.000000
mean         10.681024
std         157.399272
min           1.000000
25%           1.000000
50%           4.000000
75%          11.000000
max       80995.000000
Name: Quantity, dtype: float64

In [12]:
# Check Negative Unit Prices

df["UnitPrice"].describe()

count    525462.000000
mean          3.876109
std          42.040021
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       13541.330000
Name: UnitPrice, dtype: float64

In [13]:
(df["UnitPrice"] <= 0).sum()

np.int64(584)

In [14]:
#  Removed Negative Unit Prices

df = df[df["UnitPrice"] > 0]

df["UnitPrice"].describe()

count    524878.000000
mean          3.922573
std          36.093028
min           0.001000
25%           1.250000
50%           2.080000
75%           4.130000
max       13541.330000
Name: UnitPrice, dtype: float64

In [15]:
# 9. Create Revenue Column

df["Revenue"] = df["Quantity"] * df["UnitPrice"]

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [16]:
# 10. Final Dataset Check  

df.shape

(524878, 9)

In [17]:
#   Export to SQL

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:vasu170402@localhost:5432/ecommerce_sales_analysis"
)

df.to_sql(
    "ecommerce_sales_analysis",
    engine,
    if_exists="replace",
    index=False
)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "ecommerce_sales_analysis" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)